<?php

$groups = array(array('public','town'),array('Cult of the Vengeful Wombat','Cult of the Vengeful Wombat'),array('Cult of the Egg-Shaped Anvil','Cult of the Egg-Shaped Anvil'),array('Cult of the Wise Avacado','Cult of the Wise Avacado'),array('Corleone crime family','Corleone crime family'),array('Tattaglia crime family','Tattaglia crime family'),array('Barzini crime family','Barzini crime family'),array('Cuneo crime family','Cuneo crime family'),array('Stracci crime family','Stracci crime family'),array('Royal Arch masons','Serial Killer'),array('York Rite College masons','Cannibal'),array('Cryptic masons','Psychopath'),array('Knights Templar masons','Pyromaniac'));

?>
